### ISSUE TITLE
Import file - "UK list of exempted shares"

### ISSUE THREAD

**Issue by brunopacheco1** [Ezzinehajar/file-orchestrator#5]
### What

Create an endpoint to import [uk-list-exempted-shares.xlsx](https://www.fca.org.uk/publication/documents/uk-list-exempted-shares.xlsx) into the database.

Each file is a unique process and will be persisted in a designated table. 

*Endpoint*

POST /api/v1/uk-list-exempted-shares

Response Code: 201 - CREATED

Response body: ProcessResponse

*Schema*
- Based on the file, create a table for:
  - Issuer 
  - UkListOfExemptedShares

### Why

We will later fetch securities by ISIN.

### Deliverables

- Create an endpoint
- Create JPA Entities
- Create Liquibase configuration

### What will we cover?
- Java Collection Map
- SQL
- Liquibase
- REST
- Spring Data
- Apache POI (read Excel file)

**Comment by Ezzinehajar** [comment]
https://www.baeldung.com/java-choose-list-set-queue-map
